name: paymentwallet
description: "A new Flutter project for PP."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  google_nav_bar: ^5.0.6
  firebase_core: ^2.15.1
  firebase_auth: ^4.9.0
  cloud_firestore: ^4.9.1
  firebase_storage: ^11.2.6
  country_code_picker: ^3.0.0
  pinput: ^4.0.0
  provider: ^6.1.2
  image_picker: ^1.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:

  uses-material-design: true

  assets:
    - images/

  fonts:
    - family: Inter
      fonts:
        - asset: fonts/Inter-Regular.ttf

    - family: Poppins
      fonts:
        - asset: fonts/Poppins-Regular.ttf
